# Generated by Django 4.1.3 on 2022-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority", "deadline"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("1 - Urgent", "1 - Urgent"),
                    ("2 - High", "2 - High"),
                    ("3 - Medium", "3 - Medium"),
                    ("4 - Low", "4 - Low"),
                    ("5 - Lowest", "5 - Lowest"),
                ],
                default="5 - Lowest",
                max_length=15,
            ),
        ),
    ]
